version: '3'

services:
  selenium:
    # selenium standalone-chrome으로도 작동하는 것 확인
    image: selenium/standalone-chrome
    shm_size: 512mb
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

