spring:
  application:
    name: githubsub
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

selenium:
  url: http://localhost:4444
